// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCHEBKA.Models;

#nullable disable

namespace UCHEBKA.Migrations
{
    [DbContext(typeof(UchebnayaLeto2025Context))]
    partial class UchebnayaLeto2025ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UCHEBKA.Models.Activity", b =>
                {
                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("Activity_ID");

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Activity_Name");

                    b.Property<int?>("ActivityScore")
                        .HasColumnType("int")
                        .HasColumnName("Activity_Score");

                    b.HasKey("ActivityId")
                        .HasName("PK__Activity__393F5BA573E56DB6");

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.ActivityEvent", b =>
                {
                    b.Property<long>("ActivityEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("Activity_Event_ID");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<long?>("FkActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Activity_ID");

                    b.Property<long?>("FkEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Event_ID");

                    b.Property<long?>("FkModId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Mod_ID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Start_Time");

                    b.HasKey("ActivityEventId")
                        .HasName("PK__Activity__C338358757DE83FD");

                    b.HasIndex("FkActivityId");

                    b.HasIndex("FkEventId");

                    b.ToTable("Activity_Event", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.City", b =>
                {
                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("CityID");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("City_Name");

                    b.Property<string>("CityUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("City_Url");

                    b.HasKey("CityId")
                        .HasName("PK__City__F2D21A960164C04E");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.CityEvent", b =>
                {
                    b.Property<long>("CityEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("City_Event_ID");

                    b.Property<long?>("FkCityId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_City_ID");

                    b.Property<long?>("FkEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Event_ID");

                    b.HasKey("CityEventId")
                        .HasName("PK__City_Eve__E73D0A9421FACA5B");

                    b.HasIndex("FkCityId");

                    b.HasIndex("FkEventId");

                    b.ToTable("City_Event", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.Country", b =>
                {
                    b.Property<long>("CountryCode")
                        .HasColumnType("bigint");

                    b.Property<string>("CountryCode2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Country_Code2");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Country_Name");

                    b.Property<string>("CountryNameEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Country_Name_EN");

                    b.HasKey("CountryCode")
                        .HasName("PK__Country__5D9B0D2D9D59B178");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("EventID");

                    b.Property<int?>("EventDuration")
                        .HasColumnType("int")
                        .HasColumnName("Event_Duration");

                    b.Property<string>("EventLogoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Event_logoURL");

                    b.Property<DateTime?>("EventStartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Event_Start_Time");

                    b.Property<string>("EventTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Event_Title");

                    b.HasKey("EventId")
                        .HasName("PK__Event__7944C870E55878B3");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.EventEventType", b =>
                {
                    b.Property<long>("EventEvenTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("Event_EvenTypeID");

                    b.Property<long?>("FkEvenTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_EvenType_ID");

                    b.Property<long?>("FkEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Event_ID");

                    b.HasKey("EventEvenTypeId")
                        .HasName("PK__Event_Ev__E1B0866A3D0758E9");

                    b.HasIndex("FkEvenTypeId");

                    b.HasIndex("FkEventId");

                    b.ToTable("Event_EventType", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.EventJury", b =>
                {
                    b.Property<long>("EventJuryId")
                        .HasColumnType("bigint")
                        .HasColumnName("Event_Jury_ID");

                    b.Property<long?>("FkActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Activity_ID");

                    b.Property<long?>("FkEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Event_ID");

                    b.Property<long?>("FkJuryId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Jury_ID");

                    b.HasKey("EventJuryId")
                        .HasName("PK__Event_Ju__D92ACCB5DC74D827");

                    b.HasIndex("FkActivityId");

                    b.HasIndex("FkEventId");

                    b.HasIndex("FkJuryId");

                    b.ToTable("Event_Jury", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.EventType", b =>
                {
                    b.Property<long>("EventTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("EventTypeID");

                    b.Property<string>("EventTypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EventType_Name");

                    b.HasKey("EventTypeId")
                        .HasName("PK__EventTyp__A9216B1FABED362B");

                    b.ToTable("EventType", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Role_Name");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A7198897A");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UCHEBKA.Models.Section", b =>
                {
                    b.Property<long>("SecId")
                        .HasColumnType("bigint")
                        .HasColumnName("SecID");

                    b.Property<string>("SecName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sec_Name");

                    b.HasKey("SecId")
                        .HasName("PK__Section__14A3699F8F65F1EC");

                    b.ToTable("Section", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.SectionEvent", b =>
                {
                    b.Property<long>("SecEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("Sec_Event_ID");

                    b.Property<long?>("FkEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Event_ID");

                    b.Property<long?>("FkSecId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Sec_ID");

                    b.HasKey("SecEventId")
                        .HasName("PK__Section___CF4E4853B823711E");

                    b.HasIndex("FkEventId");

                    b.HasIndex("FkSecId");

                    b.ToTable("Section_Event", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.Sex", b =>
                {
                    b.Property<long>("SexId")
                        .HasColumnType("bigint")
                        .HasColumnName("SexID");

                    b.Property<string>("SexName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sex_Name");

                    b.HasKey("SexId")
                        .HasName("PK__Sex__75622DB6A0856907");

                    b.ToTable("Sex", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<DateTime?>("UserBirthDay")
                        .HasColumnType("datetime")
                        .HasColumnName("User_BirthDay");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Email");

                    b.Property<string>("UserLastname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Lastname");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Name");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Password");

                    b.Property<string>("UserPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Phone");

                    b.Property<string>("UserPhoto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Photo");

                    b.Property<string>("UserSurname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Surname");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC157B16E9");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UCHEBKA.Models.UserCountry", b =>
                {
                    b.Property<long>("UserCountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_CountryID");

                    b.Property<long?>("FkCountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Country_ID");

                    b.Property<long?>("FkUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_User_ID");

                    b.HasKey("UserCountryId")
                        .HasName("PK__User_Cou__56010421769BD516");

                    b.HasIndex("FkCountryId");

                    b.HasIndex("FkUserId");

                    b.ToTable("User_Country", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.UserEvent", b =>
                {
                    b.Property<long>("UserEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_Event_ID");

                    b.Property<long?>("FkEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Event_ID");

                    b.Property<long?>("FkUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_User_ID");

                    b.HasKey("UserEventId")
                        .HasName("PK__User_Eve__4663C0036CD0D3EA");

                    b.HasIndex("FkEventId");

                    b.HasIndex("FkUserId");

                    b.ToTable("User_Event", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.UserRole", b =>
                {
                    b.Property<long>("UserRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_Role_ID");

                    b.Property<long?>("FkRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Role_ID");

                    b.Property<long?>("FkUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_User_ID");

                    b.HasKey("UserRoleId")
                        .HasName("PK__User_Rol__134E48EC93C851D8");

                    b.HasIndex("FkRoleId");

                    b.HasIndex("FkUserId");

                    b.ToTable("User_Role", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.UserSec", b =>
                {
                    b.Property<long>("UserSecId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_Sec_ID");

                    b.Property<long?>("FkSecId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Sec_ID");

                    b.Property<long?>("FkUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_User_ID");

                    b.HasKey("UserSecId")
                        .HasName("PK__User_Sec__99DF19A4703F9DD2");

                    b.HasIndex("FkSecId");

                    b.HasIndex("FkUserId");

                    b.ToTable("User_Sec", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.UserSex", b =>
                {
                    b.Property<long>("UserSecId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_Sec_ID");

                    b.Property<long?>("FkSexId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_Sex_ID");

                    b.Property<long?>("FkUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_User_ID");

                    b.HasKey("UserSecId")
                        .HasName("PK__User_Sex__99DF19A4AB466115");

                    b.HasIndex("FkSexId");

                    b.HasIndex("FkUserId");

                    b.ToTable("User_Sex", (string)null);
                });

            modelBuilder.Entity("UCHEBKA.Models.ActivityEvent", b =>
                {
                    b.HasOne("UCHEBKA.Models.Activity", "FkActivity")
                        .WithMany("ActivityEvents")
                        .HasForeignKey("FkActivityId")
                        .HasConstraintName("FK_ActivityEvent_Activity");

                    b.HasOne("UCHEBKA.Models.Event", "FkEvent")
                        .WithMany("ActivityEvents")
                        .HasForeignKey("FkEventId")
                        .HasConstraintName("FK_ActivityEvent_Event");

                    b.Navigation("FkActivity");

                    b.Navigation("FkEvent");
                });

            modelBuilder.Entity("UCHEBKA.Models.CityEvent", b =>
                {
                    b.HasOne("UCHEBKA.Models.City", "FkCity")
                        .WithMany("CityEvents")
                        .HasForeignKey("FkCityId")
                        .HasConstraintName("FK_CityEvent_City");

                    b.HasOne("UCHEBKA.Models.Event", "FkEvent")
                        .WithMany("CityEvents")
                        .HasForeignKey("FkEventId")
                        .HasConstraintName("FK_CityEvent_Event");

                    b.Navigation("FkCity");

                    b.Navigation("FkEvent");
                });

            modelBuilder.Entity("UCHEBKA.Models.EventEventType", b =>
                {
                    b.HasOne("UCHEBKA.Models.EventType", "FkEvenType")
                        .WithMany("EventEventTypes")
                        .HasForeignKey("FkEvenTypeId")
                        .HasConstraintName("FK_EventEventType_EventType");

                    b.HasOne("UCHEBKA.Models.Event", "FkEvent")
                        .WithMany("EventEventTypes")
                        .HasForeignKey("FkEventId")
                        .HasConstraintName("FK_EventEventType_Event");

                    b.Navigation("FkEvenType");

                    b.Navigation("FkEvent");
                });

            modelBuilder.Entity("UCHEBKA.Models.EventJury", b =>
                {
                    b.HasOne("UCHEBKA.Models.Activity", "FkActivity")
                        .WithMany("EventJuries")
                        .HasForeignKey("FkActivityId")
                        .HasConstraintName("FK_EventJury_Activity");

                    b.HasOne("UCHEBKA.Models.Event", "FkEvent")
                        .WithMany("EventJuries")
                        .HasForeignKey("FkEventId")
                        .HasConstraintName("FK_EventJury_Event");

                    b.HasOne("UCHEBKA.Models.User", "FkJury")
                        .WithMany("EventJuries")
                        .HasForeignKey("FkJuryId")
                        .HasConstraintName("FK_EventJury_Jury");

                    b.Navigation("FkActivity");

                    b.Navigation("FkEvent");

                    b.Navigation("FkJury");
                });

            modelBuilder.Entity("UCHEBKA.Models.SectionEvent", b =>
                {
                    b.HasOne("UCHEBKA.Models.Event", "FkEvent")
                        .WithMany("SectionEvents")
                        .HasForeignKey("FkEventId")
                        .HasConstraintName("FK_SectionEvent_Event");

                    b.HasOne("UCHEBKA.Models.Section", "FkSec")
                        .WithMany("SectionEvents")
                        .HasForeignKey("FkSecId")
                        .HasConstraintName("FK_SectionEvent_Section");

                    b.Navigation("FkEvent");

                    b.Navigation("FkSec");
                });

            modelBuilder.Entity("UCHEBKA.Models.UserCountry", b =>
                {
                    b.HasOne("UCHEBKA.Models.Country", "FkCountry")
                        .WithMany("UserCountries")
                        .HasForeignKey("FkCountryId")
                        .HasConstraintName("FK_UserCountry_Country");

                    b.HasOne("UCHEBKA.Models.User", "FkUser")
                        .WithMany("UserCountries")
                        .HasForeignKey("FkUserId")
                        .HasConstraintName("FK_UserCountry_User");

                    b.Navigation("FkCountry");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("UCHEBKA.Models.UserEvent", b =>
                {
                    b.HasOne("UCHEBKA.Models.Event", "FkEvent")
                        .WithMany("UserEvents")
                        .HasForeignKey("FkEventId")
                        .HasConstraintName("FK_UserEvent_Event");

                    b.HasOne("UCHEBKA.Models.User", "FkUser")
                        .WithMany("UserEvents")
                        .HasForeignKey("FkUserId")
                        .HasConstraintName("FK_UserEvent_User");

                    b.Navigation("FkEvent");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("UCHEBKA.Models.UserRole", b =>
                {
                    b.HasOne("UCHEBKA.Models.Role", "FkRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("FkRoleId")
                        .HasConstraintName("FK_UserRole_Role");

                    b.HasOne("UCHEBKA.Models.User", "FkUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("FkUserId")
                        .HasConstraintName("FK_UserRole_User");

                    b.Navigation("FkRole");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("UCHEBKA.Models.UserSec", b =>
                {
                    b.HasOne("UCHEBKA.Models.Section", "FkSec")
                        .WithMany("UserSecs")
                        .HasForeignKey("FkSecId")
                        .HasConstraintName("FK_UserSec_Section");

                    b.HasOne("UCHEBKA.Models.User", "FkUser")
                        .WithMany("UserSecs")
                        .HasForeignKey("FkUserId")
                        .HasConstraintName("FK_UserSec_User");

                    b.Navigation("FkSec");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("UCHEBKA.Models.UserSex", b =>
                {
                    b.HasOne("UCHEBKA.Models.Sex", "FkSex")
                        .WithMany("UserSexes")
                        .HasForeignKey("FkSexId")
                        .HasConstraintName("FK_UserSex_Sex");

                    b.HasOne("UCHEBKA.Models.User", "FkUser")
                        .WithMany("UserSexes")
                        .HasForeignKey("FkUserId")
                        .HasConstraintName("FK_UserSex_User");

                    b.Navigation("FkSex");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("UCHEBKA.Models.Activity", b =>
                {
                    b.Navigation("ActivityEvents");

                    b.Navigation("EventJuries");
                });

            modelBuilder.Entity("UCHEBKA.Models.City", b =>
                {
                    b.Navigation("CityEvents");
                });

            modelBuilder.Entity("UCHEBKA.Models.Country", b =>
                {
                    b.Navigation("UserCountries");
                });

            modelBuilder.Entity("UCHEBKA.Models.Event", b =>
                {
                    b.Navigation("ActivityEvents");

                    b.Navigation("CityEvents");

                    b.Navigation("EventEventTypes");

                    b.Navigation("EventJuries");

                    b.Navigation("SectionEvents");

                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("UCHEBKA.Models.EventType", b =>
                {
                    b.Navigation("EventEventTypes");
                });

            modelBuilder.Entity("UCHEBKA.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UCHEBKA.Models.Section", b =>
                {
                    b.Navigation("SectionEvents");

                    b.Navigation("UserSecs");
                });

            modelBuilder.Entity("UCHEBKA.Models.Sex", b =>
                {
                    b.Navigation("UserSexes");
                });

            modelBuilder.Entity("UCHEBKA.Models.User", b =>
                {
                    b.Navigation("EventJuries");

                    b.Navigation("UserCountries");

                    b.Navigation("UserEvents");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSecs");

                    b.Navigation("UserSexes");
                });
#pragma warning restore 612, 618
        }
    }
}
